### ISSUE TITLE
Sadly there is a bug in prime

### ISSUE THREAD

**Issue by chambart** [marklrh/jaw#6]
The addition is incorrect, for instance four is not 2 + 2 in this definition:

```OCaml
type four = z s s s s

type ('a, 'b, 'c) addable = A of ('a, 'b, 'c) add

let v : (two, two, four) addable neg = function
  | A (Zr (Zr _)) -> .
```

Note that this can of course be fixed. Of course the base case of the addition is `0 + n = 0` rather than the more restricted `0 + 0 = 0`. 

```OCaml
type (_, _, _) add =
  | Zz: (z, 'a, 'a) add
  | Zr: ('a, 'b, 'c) add -> ('a, 'b s, 'c s) add
```
The remaining of the proof still works, you only have to add a few more cases to it:

```OCaml
let two_is_prime : two prime = function
  | C (Mn (Mone, Zr Zr _)) -> .
  | C (Mn (Mn _, Zr Zr _)) -> .
  | C (Mn (Mn (_, _), Zr Zz)) -> .
  | C (Mn (Mn (_, _), Zz)) -> .
```

**Comment by objmagic** [comment]
Thanks, Pierre. I will fix the code!

**Comment by objmagic** [comment]
Fixed. Thanks!!
